/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      height: {
        screen: ['100vh /* fallback for Opera, IE and etc. */', '100dvh'],
        '10vw': '10vw',
        '15vw': '15vw',
        '20vw': '20vw',
        '1r': '1rem',
        '2r': '2rem',
        '3r': '3rem',
        '4r': '4rem',
        '5r': '5rem',
        '6r': '6rem',
        '7r': '7rem',
        '8r': '8rem',
        '25p': '25%',
        '30p': '30%', 
        '40p': '40%', 
        '50p': '50%',   
        '60p': '60%',   
        '70p': '70%', 
        '75p': '75%', 
        '80p': '80%',  
        '90p': '90%',   
        '100p': '100%',
        '110p': '110%', 
        '120p': '120%',
        '125p': '125%',
        '130p': '130%', 
        '140p': '140%', 
        '150p': '150%', 
        '160p': '160%', 
        '170p': '170%', 
        '180p': '180%', 
        '190p': '190%', 
        '200p': '200%', 
      },
      width: {
        screen: ['100vh /* fallback for Opera, IE and etc. */', '100dvh'],
        '10vw': '10vw',
        '15vw': '15vw',
        '20vw': '20vw',
        '1r': '1rem',
        '2r': '2rem',
        '3r': '3rem',
        '4r': '4rem',
        '5r': '5rem',
        '6r': '6rem',
        '7r': '7rem',
        '8r': '8rem',
        '25p': '25%',
        '30p': '30%', 
        '40p': '40%', 
        '50p': '50%',   
        '60p': '60%',   
        '70p': '70%', 
        '75p': '75%', 
        '80p': '80%',  
        '90p': '90%',   
        '100p': '100%',
        '110p': '110%', 
        '120p': '120%',
        '125p': '125%',
        '130p': '130%', 
        '140p': '140%', 
        '150p': '150%', 
        '160p': '160%', 
        '170p': '170%', 
        '180p': '180%', 
        '190p': '190%', 
        '200p': '200%', 
      },
      fontSize: {
        '1r': '1rem',
        '2r': '2rem',
        '3r': '3rem',
        '4r': '4rem',
        '5r': '5rem',
        '6r': '6rem',
        '7r': '7rem',
        '8r': '8rem',
        '20vh': '20vh',
        '25vh': '25vh',
        '4vw': '4vw',
        '6vw': '6vw',
        '25p': '25%',
        '30p': '30%', 
        '40p': '40%', 
        '50p': '50%',   
        '60p': '60%',   
        '70p': '70%', 
        '75p': '75%', 
        '80p': '80%',  
        '90p': '90%',   
        '100p': '100%',
        '110p': '110%', 
        '120p': '120%',
        '125p': '125%',
        '130p': '130%', 
        '140p': '140%', 
        '150p': '150%', 
        '160p': '160%', 
        '170p': '170%', 
        '180p': '180%', 
        '190p': '190%', 
        '200p': '200%', 
      },
      margin: {
        '10p': '10%',
      },
      fontFamily: {
        sans: ['var(--font-icon)'],
      },
      minHeight: (theme: any) => ({
        ...theme('spacing'),
      }),
      spacing: {
        preview: 'var(--preview-size)',
        'preview-height': 'var(--preview-card-height)',
        nav: 'var(--nav)',
      },
      colors: {
        brand: 'hsl(var(--brand))',
        success: 'hsl(var(--success))',
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
        'slide-in': {
          '0%': {
            transform: 'translateX(100%)',
          },
          '100%': {
            transform: 'translateX(0)',
          },
        },
        popup: {
          '0%': { transform: 'translateX(-100%)' },

          '100%': { transform: 'translateX(0)' },
        },
        spin: {
          '0%': {
            transform: 'rotate(0deg)',
          },
          '100%': {
            transform: 'rotate(360deg)',
          },
        },
        appear: {
          '0%': {
            opacity: 0,
          },
          '100%': {
            opacity: 1,
          },
        },
        expand: {
          '0%': { transform: 'scaleY(0)' },
          '100%': { transform: 'scaleY(1)' },
        },
        collapse: {
          '0%': { transform: 'scaleY(1)' },
          '100%': { transform: 'scaleY(0)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'slide-in': 'slide-in 0.5s forwards',
        popup: 'popup 0.2s forwards',
        spin: 'spin 1s linear infinite',
        appear: 'appear 1s',
        expand: 'expand 1s linear forwards',
        collapse: 'collapse 1s linear forwards',
      },
    },
  },
  plugins: [require('tailwindcss-animate'), require('@tailwindcss/typography')],
};
