import { ServerStatus } from '@/constant/constant';
import { ServerMode } from '@/types/request/UpdateServerRequest';
import { ServerPlan } from '@/types/response/ServerPlan';

export type ServerDto = {
	id: string;
	name: string;
	userId: string;
	description: string;
	port: number;
	isOfficial: boolean;
	mode: ServerMode;
	gamemode?: string;
	status: ServerStatus;
	ramUsage: number;
	cpuUsage: number;
	totalRam: number;
	players: number;
	mapName: string;
	address: string;
	avatar: string;
	discordChannelId: string | null;
	isAutoTurnOff: boolean;
	isHub: boolean;
	isPaused: boolean;
	hostCommand?: string;
	kicks: number;
	errors: string[];
	planId: number;
	plan: ServerPlan;
};
